// Generated by JSPP compiler

#include <iostream>
#include <string>
#include <vector>

template<typename... Args>
void print(Args&&... args) {
    bool __first = true;
    ((std::cout << (__first ? "" : " ") << args, __first = false), ...);
    std::cout << std::endl;
}

template<typename T>
void __jspp_set(std::vector<T>& v, size_t i, T val) {
    if (i >= v.size()) v.resize(i + 1);
    v[i] = std::move(val);
}

struct __anon_0 {
    std::string name;
    int hp;
    int damage;
};

auto add(auto a, auto b) {
    return (a + b);
}

auto makeCounter(auto start) {
    auto n = start;
    return [=]() mutable {
        n = (n + 1);
        return n;
    };
}

auto map(auto array, auto fn) {
    std::vector<int> out = std::vector<int>{};
    for (int i = 0; (i < array.size()); i = (i + 1)) {
        __jspp_set(out, (size_t)(i), fn(array[i]));
    }
    return out;
}

auto factorial(auto n) {
    if ((n <= 1)) {
        return 1;
    }
    return (n * factorial((n - 1)));
}

auto grade(auto score) {
    if ((score >= 90)) {
        return "A";
    }
    if ((score >= 80)) {
        return "B";
    }
    if ((score >= 70)) {
        return "C";
    }
    return "D";
}

int main() {
    int x = 5;
    int y = 7;
    auto z = (x * y);
    print("z:", z);
    print("add(10, 20):", add(10, 20));
    auto counter = makeCounter(3);
    print("counter():", counter());
    print("counter():", counter());
    std::vector<int> arr = std::vector<int>{1, 2, 3, 4};
    int arrSum = 0;
    for (int i = 0; (i < arr.size()); i = (i + 1)) {
        arrSum = (arrSum + arr[i]);
    }
    print("arrSum:", arrSum);
    auto player = __anon_0{"Enzo", 10, 3};
    print("player.hp:", player.hp);
    player.hp = (player.hp - player.damage);
    print("player.hp after hit:", player.hp);
    auto doubled = map(std::vector<int>{2, 4, 6}, [=](auto n) mutable {
        return (n * 2);
    });
    print("doubled[1]:", doubled[1]);
    print("factorial(5):", factorial(5));
    print("grade(86):", grade(86));
    return 0;
}
