// Expected C++ output for test_basic.jspp
// Generated by JSPP compiler

#include <iostream>
#include <string>
#include <vector>
#include <functional>

// --- JSPP runtime helpers ---

template<typename... Args>
void print(Args&&... args) {
    bool __first = true;
    ((std::cout << (__first ? "" : " ") << args, __first = false), ...);
    std::cout << std::endl;
}

template<typename T>
void __jspp_set(std::vector<T>& v, size_t i, T val) {
    if (i >= v.size()) v.resize(i + 1);
    v[i] = std::move(val);
}

// --- Basic values ---
auto x = 5;
auto y = 7;
auto z = x * y;

// --- Functions ---
auto add(auto a, auto b) {
    return a + b;
}

// --- Closures ---
auto makeCounter(auto start) {
    auto n = start;
    return [n]() mutable {
        n = n + 1;
        return n;
    };
}

// --- Higher-order functions ---
template<typename T, typename F>
auto map(std::vector<T> array, F fn) {
    std::vector<decltype(fn(array[0]))> out;
    for (size_t i = 0; i < array.size(); i = i + 1) {
        if (i >= out.size()) out.resize(i + 1);
        out[i] = fn(array[i]);
    }
    return out;
}

// --- Recursion ---
int factorial(int n) {
    if (n <= 1) return 1;
    return n * factorial(n - 1);
}

// --- Conditionals ---
std::string grade(int score) {
    if (score >= 90) return "A";
    if (score >= 80) return "B";
    if (score >= 70) return "C";
    return "D";
}

int main() {
    print("z:", z);

    print("add(10, 20):", add(10, 20));

    auto counter = makeCounter(3);
    print("counter():", counter());
    print("counter():", counter());

    std::vector<int> arr = {1, 2, 3, 4};
    int arrSum = 0;

    for (size_t i = 0; i < arr.size(); i = i + 1) {
        arrSum = arrSum + arr[i];
    }

    print("arrSum:", arrSum);

    struct __anon_player { std::string name; int hp; int damage; };
    __anon_player player = {"Enzo", 10, 3};

    print("player.hp:", player.hp);
    player.hp = player.hp - player.damage;
    print("player.hp after hit:", player.hp);

    auto doubled = map(std::vector<int>{2, 4, 6}, [](auto n) { return n * 2; });

    print("doubled[1]:", doubled[1]);

    print("factorial(5):", factorial(5));

    print("grade(86):", grade(86));

    return 0;
}
